script:
- (DIR=$(pwd); cd foo; for f in $(find -name ".surefire*"); do cp --parents ${f} ${DIR}/; done)
- mvn test
- for f in $(find -name ".surefire*"); do cp --parents ${f} foo/; done

cache:
    directories:
    - foo/
