script: echo TRAVIS RANGE ${TRAVIS_COMMIT_RANGE} && git diff --name-status ${TRAVIS_COMMIT_RANGE} && if [[ -d foo/ ]]; then echo EXISTS!!!!; else echo MISSING!!!; mkdir foo/; fi

cache:
    directories:
    - foo/
